apiVersion: v1
kind: Secret
metadata:
  namespace: capstone-gbc
  name: backend-secret
type: Opaque
data:
  mongo-url: bW9uZ29kYitzcnY6Ly9ha3VsOmFrdWxAY2x1c3RlcjAuMWNpbW0ubW9uZ29kYi5uZXQvP3JldHJ5V3JpdGVzPXRydWUmdz1tYWpvcml0eSZhcHBOYW1lPUNsdXN0ZXIwCg==
