apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: capstone-gbc
spec:
  capacity:
    storage: 200Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/db
