apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: capstone-gbc
  labels:
    role: api
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      imagePullSecrets:
        - name: ecr-registry-secret
      containers:
        - name: api
          image: public.ecr.aws/w3w7t4h3/todo-backend:latest
          imagePullPolicy: Always
          env:
            - name: MONGO_CONN_STR
              value: MONGODB_URI = mongodb+srv://mongodb-svc@cluster0.1cimm.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: username
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-sec
                  key: password
          ports:
            - containerPort: 3500
          livenessProbe:
            httpGet:
              path: /ok
              port: 3500
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ok
              port: 3500
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
